"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2z*&rg!%vl03^jh=ns6-y1k$u)=$3rgdx%fmh#a2%wjhr)z7j4'

# SECURITY WARNING: don't run with debug turned on in production!
# 1. DEBUG режимин өчүрөбүз
# 1. DEBUG режимин өчүрөбүз
DEBUG = True

# 2. Хостторду аныктайбыз
# Боштукту (пробелди) алып салыңыз
ALLOWED_HOSTS = ['*']

# 3. CSRF коопсуздугу
CSRF_TRUSTED_ORIGINS = ['https://travel-kg-5.onrender.com']

# Application definition
INSTALLED_APPS = [
    'cloudinary_storage',          # 1. Эң биринчи ушул турушу керек
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', # 2. Бул ар дайым 'cloudinary_storage' дан кийин
    'cloudinary',                 # 3. Бул жерге кошсоң болот
    'main',                       # 4. Сенин колдонмоң (app)
] # <--- Кашаа жабылганын текшериңиз
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # 1. Сессияны ачат
    'django.middleware.locale.LocaleMiddleware',           # 2. Тилди аныктайт (УШУЛ ЖЕРГЕ КОШУҢУЗ)
    'django.middleware.common.CommonMiddleware',           # 3. Калган иштерди жасайт
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


    # Internationalization
    # https://docs.djangoproject.com/en/6.0/topics/i18n/

# Башка жөндөөлөрдүн астында, эң сол четинде болушу шарт
LANGUAGES = [
    ('ky', 'Kyrgyz'),
    ('ru', 'Russian'),
    ('en', 'English'),
]
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


import os
from pathlib import Path

# Бул жерде BASE_DIR жогоруда аныкталган болушу керек, бирок коопсуздук үчүн калтырдык
BASE_DIR = Path(__file__).resolve().parent.parent

# 1. Статикалык файлдар (CSS, JS)
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 2. Медиа файлдар (Сүрөттөр)
MEDIA_URL = '/media/'

# 3. Cloudinary жөндөөлөрү
# ЭСКЕРТҮҮ: API_SECRET деген жерге чыныгы кодуңду жаз!
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dffggv57z',
    'API_KEY': '159731443338952',
    'API_SECRET': 'CLOUDINARY_URL=cloudinary://<your_api_key>:<your_api_secret>@dffggv57z'
}

# 4. Django 6.0 үчүн STORAGES жөндөөсү
# Бул бөлүк эски STATICFILES_STORAGE жөндөөсүн алмаштырат
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "cloudinary_storage.storage.StaticCloudinaryStorage",
    },
}