# Generated by Django 6.0.3 on 2026-03-12 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_tour_duration_remove_tour_image_tour_features_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-created_at'], 'verbose_name': 'Тур', 'verbose_name_plural': 'Турлар'},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='features',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='image_url',
        ),
        migrations.AddField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.CharField(default='1 күн', max_length=50, verbose_name='Узактыгы'),
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Сүрөт'),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активдүүбү?'),
        ),
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='Толук маалымат'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баасы'),
        ),
    ]
