# Generated by Django 6.0.3 on 2026-03-12 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tour_options_remove_tour_features_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='slug',
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='Маалымат'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tour')),
            ],
        ),
    ]
