# Generated by Django 6.0.3 on 2026-03-13 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_tour_options_remove_tour_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активдүү'),
        ),
        migrations.AddField(
            model_name='tour',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ирет номери'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Кардардын аты-жөнү'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_orders', to='main.tour', verbose_name='Тур'),
        ),
    ]
